version: "3.9"

services:
  db:
    image: postgres:16
    container_name: cine_delices_db
    restart: always
    environment:
      POSTGRES_USER: cine
      POSTGRES_PASSWORD: cinepass
      POSTGRES_DB: cinedelices
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    container_name: cine_delices_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://cine:cinepass@db:5432/cinedelices
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules

  client:
    container_name: cine-delices-client
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: npm run dev -- --host

volumes:
  db_data: